### ISSUE TITLE
这如何解决

### ISSUE THREAD

**Issue by 448808614** [TonyNomoney/Coishi#2]
[IOException] bind failed: EADDRINUSE (Address already in use)

**Comment by TonyNomoney** [comment]
> [IOException] bind failed: EADDRINUSE (Address already in use)

Maybe you have used the necessary port, please try to restart your app or reboot your device. If this doesn't work , try to change the listenning port of Online-Log.
可能必要的端口已经被使用了，试试关闭后台重启应用或者重启你的设备，如果没用的话，改一下源码中的在线日志监听端口试试？

**Comment by 448808614** [comment]
好的👌
